version: '3.6'
services:
  nginx:
    image: nginx:latest
    container_name: jw-nginx
    networks:
      - jw_network
    depends_on:
      - php-xdebug
    ports:
      - ${NGINX_XDEBUG_PORT}:8198
      - ${NGINX_XDEBUG_PORT_WITH_SSH}:8196
    volumes:
      - .docker/nginx/templates:/etc/nginx/templates
      - ./:/var/www/html:ro
      - ./:/var/www/html-ssh:ro
      - "phpsocket:/var/run"
      - "socket:/var/run/xdebug"
    environment:
      NGINX_WEBSOCKET_LISTENER_PORT: ${NGINX_WEBSOCKET_LISTENER_PORT}

  php-xdebug:
    build:
      context: .docker/php
    container_name: jw-php-xdebug
    ports:
      - "10025:22"
    networks:
      - jw_network
    volumes:
      - ./:/var/www/html/:cached
      - .docker/php/php.ini:/usr/local/etc/php/conf.d/docker-tracker.ini
      - .docker/php/xdebug-on.ini:/usr/local/etc/php/conf.d/xdebug-on.ini
      - .docker/php/zz-docker-xdebug.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - "socket:/var/run/xdebug"
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal idekey=PHPSTORM"
      PHP_IDE_CONFIG: "serverName=Jw"

  mysql:
    image: mysql:8
    container_name: jw-mysql
    networks:
      - jw_network
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./var/db:/var/lib/mysql

# Uncomment if it need
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    container_name: wrs-tracker-phpmyadmin
#    networks:
#      - tm_network
#    environment:
#      - PMA_HOST=${PHPMYADMIN_HOST}
#      - PMA_USER=${PHPMYADMIN_USER}
#      - PMA_PASSWORD=${PHPMYADMIN_PASSWORD}
#    ports:
#      - ${PHPMYADMIN_PORT}:80
#    volumes:
#      - /sessions
#    links:
#      - mysql

###> doctrine/doctrine-bundle ###
#  database:
#    image: postgres:${POSTGRES_VERSION:-15}-alpine
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB:-app}
#      # You should definitely change the password in production
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
#      POSTGRES_USER: ${POSTGRES_USER:-app}
#    volumes:
#      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

networks:
  jw_network:
    driver: bridge

volumes:
  phpsocket:
  socket:

###> doctrine/doctrine-bundle ###
#  database_data:
###< doctrine/doctrine-bundle ###
